import type { DeptRecord, MenuRecord, RoleRecord } from '../model/admin-records'

export const fallbackRoles: RoleRecord[] = [
  { id: 1, name: '超级管理员', code: 'admin', status: 1, remark: '拥有系统全部权限', permissions: ['*:*:*'], createdAt: new Date().toISOString() },
  { id: 2, name: '普通用户', code: 'user', status: 1, remark: '拥有基础访问权限', permissions: ['permission:page:view', 'permission:button:view'], createdAt: new Date().toISOString() },
]

export const fallbackMenus: MenuRecord[] = [
  { id: 14, parentId: null, title: '仪表盘', path: '/dashboard', name: 'Dashboard', icon: 'dashboard', permission: null, type: 'catalog', sort: 1, status: 1 },
  { id: 15, parentId: 14, title: '仪表盘', path: '/dashboard/index', name: 'DashboardView', icon: 'dashboard', permission: null, type: 'menu', sort: 1, status: 1 },
  { id: 1, parentId: null, title: '权限管理', path: '/permission', name: 'Permission', icon: 'permission', permission: null, type: 'catalog', sort: 20, status: 1 },
  { id: 2, parentId: 1, title: '页面权限', path: '/permission/page', name: 'PagePermission', icon: 'permission', permission: 'permission:page:view', type: 'menu', sort: 1, status: 1 },
  { id: 3, parentId: 1, title: '按钮权限', path: '/permission/button', name: 'ButtonPermission', icon: 'permission', permission: 'permission:button:view', type: 'menu', sort: 2, status: 1 },
  { id: 4, parentId: null, title: '系统监控', path: '/monitor', name: 'Monitor', icon: 'monitor', permission: null, type: 'catalog', sort: 30, status: 1 },
  { id: 5, parentId: 4, title: '在线用户', path: '/monitor/online-user', name: 'OnlineUser', icon: 'monitor', permission: 'monitor:online:view', type: 'menu', sort: 1, status: 1 },
  { id: 6, parentId: 4, title: '登录日志', path: '/monitor/login-logs', name: 'LoginLogs', icon: 'monitor', permission: 'log:login:view', type: 'menu', sort: 2, status: 1 },
  { id: 7, parentId: 4, title: '操作日志', path: '/monitor/operation-logs', name: 'OperationLogs', icon: 'monitor', permission: 'log:operation:view', type: 'menu', sort: 3, status: 1 },
  { id: 8, parentId: 4, title: '系统日志', path: '/monitor/system-logs', name: 'SystemLogs', icon: 'monitor', permission: 'log:system:view', type: 'menu', sort: 4, status: 1 },
  { id: 9, parentId: null, title: '系统管理', path: '/system', name: 'System', icon: 'system', permission: null, type: 'catalog', sort: 40, status: 1 },
  { id: 10, parentId: 9, title: '用户管理', path: '/system/user', name: 'UserList', icon: 'user', permission: 'user:view', type: 'menu', sort: 1, status: 1 },
  { id: 11, parentId: 9, title: '角色管理', path: '/system/role', name: 'RoleManagement', icon: 'role', permission: 'role:view', type: 'menu', sort: 2, status: 1 },
  { id: 12, parentId: 9, title: '菜单管理', path: '/system/menu', name: 'MenuManagement', icon: 'menu', permission: 'menu:view', type: 'menu', sort: 3, status: 1 },
  { id: 13, parentId: 9, title: '部门管理', path: '/system/dept', name: 'DeptManagement', icon: 'dept', permission: 'dept:view', type: 'menu', sort: 4, status: 1 },
  { id: 20, parentId: null, title: '业务管理', path: '/commerce', name: 'Commerce', icon: 'document', permission: null, type: 'catalog', sort: 35, status: 1 },
  { id: 21, parentId: 20, title: '商家管理', path: '/commerce/restaurant', name: 'CommerceRestaurantView', icon: 'document', permission: 'commerce:restaurant:view', type: 'menu', sort: 1, status: 1 },
  { id: 22, parentId: 20, title: '商品管理', path: '/commerce/food', name: 'CommerceFoodView', icon: 'document', permission: 'commerce:food:view', type: 'menu', sort: 2, status: 1 },
  { id: 23, parentId: 20, title: '订单管理', path: '/commerce/order', name: 'CommerceOrderView', icon: 'document', permission: 'commerce:order:view', type: 'menu', sort: 3, status: 1 },
  { id: 30, parentId: null, title: '多级菜单', path: '/nested', name: 'Nested', icon: 'nested', permission: null, type: 'catalog', sort: 50, status: 1 },
  { id: 31, parentId: 30, title: '菜单1', path: '/nested/menu1', name: 'NestedMenu1', icon: 'nested', permission: null, type: 'catalog', sort: 1, status: 1 },
  { id: 32, parentId: 31, title: '菜单1-1', path: '/nested/menu1/menu1-1', name: 'NestedMenu11View', icon: 'nested', permission: null, type: 'menu', sort: 1, status: 1 },
  { id: 33, parentId: 31, title: '菜单1-2', path: '/nested/menu1/menu1-2', name: 'NestedMenu12', icon: 'nested', permission: null, type: 'catalog', sort: 2, status: 1 },
  { id: 34, parentId: 33, title: '菜单1-2-1', path: '/nested/menu1/menu1-2/menu1-2-1', name: 'NestedMenu121View', icon: 'nested', permission: null, type: 'menu', sort: 1, status: 1 },
  { id: 35, parentId: 33, title: '菜单1-2-2', path: '/nested/menu1/menu1-2/menu1-2-2', name: 'NestedMenu122View', icon: 'nested', permission: null, type: 'menu', sort: 2, status: 1 },
  { id: 36, parentId: 31, title: '菜单1-3', path: '/nested/menu1/menu1-3', name: 'NestedMenu13View', icon: 'nested', permission: null, type: 'menu', sort: 3, status: 1 },
  { id: 37, parentId: 30, title: '菜单2', path: '/nested/menu2', name: 'NestedMenu2View', icon: 'nested', permission: null, type: 'menu', sort: 2, status: 1 },
  { id: 101, parentId: 5, title: '强制下线', path: '/monitor/online-user', name: null, icon: null, permission: 'monitor:online:force-logout', type: 'button', sort: 1, status: 1 },
  { id: 110, parentId: 10, title: '新增用户', path: '/system/user', name: null, icon: null, permission: 'user:add', type: 'button', sort: 1, status: 1 },
  { id: 111, parentId: 10, title: '编辑用户', path: '/system/user', name: null, icon: null, permission: 'user:edit', type: 'button', sort: 2, status: 1 },
  { id: 112, parentId: 10, title: '删除用户', path: '/system/user', name: null, icon: null, permission: 'user:delete', type: 'button', sort: 3, status: 1 },
  { id: 120, parentId: 11, title: '新增角色', path: '/system/role', name: null, icon: null, permission: 'role:add', type: 'button', sort: 1, status: 1 },
  { id: 121, parentId: 11, title: '编辑角色', path: '/system/role', name: null, icon: null, permission: 'role:edit', type: 'button', sort: 2, status: 1 },
  { id: 122, parentId: 11, title: '删除角色', path: '/system/role', name: null, icon: null, permission: 'role:delete', type: 'button', sort: 3, status: 1 },
  { id: 130, parentId: 12, title: '新增菜单', path: '/system/menu', name: null, icon: null, permission: 'menu:add', type: 'button', sort: 1, status: 1 },
  { id: 131, parentId: 12, title: '编辑菜单', path: '/system/menu', name: null, icon: null, permission: 'menu:edit', type: 'button', sort: 2, status: 1 },
  { id: 132, parentId: 12, title: '删除菜单', path: '/system/menu', name: null, icon: null, permission: 'menu:delete', type: 'button', sort: 3, status: 1 },
  { id: 140, parentId: 13, title: '新增部门', path: '/system/dept', name: null, icon: null, permission: 'dept:add', type: 'button', sort: 1, status: 1 },
  { id: 141, parentId: 13, title: '编辑部门', path: '/system/dept', name: null, icon: null, permission: 'dept:edit', type: 'button', sort: 2, status: 1 },
  { id: 142, parentId: 13, title: '删除部门', path: '/system/dept', name: null, icon: null, permission: 'dept:delete', type: 'button', sort: 3, status: 1 },
  { id: 150, parentId: 21, title: '新增商家', path: '/commerce/restaurant', name: null, icon: null, permission: 'commerce:restaurant:add', type: 'button', sort: 1, status: 1 },
  { id: 151, parentId: 21, title: '编辑商家', path: '/commerce/restaurant', name: null, icon: null, permission: 'commerce:restaurant:edit', type: 'button', sort: 2, status: 1 },
  { id: 152, parentId: 21, title: '删除商家', path: '/commerce/restaurant', name: null, icon: null, permission: 'commerce:restaurant:delete', type: 'button', sort: 3, status: 1 },
  { id: 160, parentId: 22, title: '新增商品', path: '/commerce/food', name: null, icon: null, permission: 'commerce:food:add', type: 'button', sort: 1, status: 1 },
  { id: 161, parentId: 22, title: '编辑商品', path: '/commerce/food', name: null, icon: null, permission: 'commerce:food:edit', type: 'button', sort: 2, status: 1 },
  { id: 162, parentId: 22, title: '删除商品', path: '/commerce/food', name: null, icon: null, permission: 'commerce:food:delete', type: 'button', sort: 3, status: 1 },
  { id: 170, parentId: 23, title: '编辑订单', path: '/commerce/order', name: null, icon: null, permission: 'commerce:order:edit', type: 'button', sort: 1, status: 1 },
]

export const fallbackDepts: DeptRecord[] = [
  { id: 1, parentId: null, name: '总公司', leader: '管理员', phone: '13800138000', email: 'admin@example.com', sort: 1, status: 1 },
  { id: 2, parentId: 1, name: '研发部门', leader: '研发负责人', phone: '13800138001', email: 'rd@example.com', sort: 1, status: 1 },
  { id: 3, parentId: 1, name: '运营部门', leader: '运营负责人', phone: '13800138002', email: 'ops@example.com', sort: 2, status: 1 },
]
