import type { ButtonPermissionRecord, PagePermissionRecord } from '../model/admin-records'

export const buttonPermissions: ButtonPermissionRecord[] = [
  {
    code: 'permission:page:view',
    name: '页面权限查看',
    group: '权限管理',
  },
  {
    code: 'permission:button:view',
    name: '按钮权限查看',
    group: '权限管理',
  },
  {
    code: 'user:view',
    name: '用户查看',
    group: '系统管理',
  },
  {
    code: 'user:add',
    name: '用户新增',
    group: '系统管理',
  },
  {
    code: 'user:edit',
    name: '用户编辑',
    group: '系统管理',
  },
  {
    code: 'user:delete',
    name: '用户删除',
    group: '系统管理',
  },
  {
    code: 'role:view',
    name: '角色查看',
    group: '系统管理',
  },
  {
    code: 'role:add',
    name: '角色新增',
    group: '系统管理',
  },
  {
    code: 'role:edit',
    name: '角色编辑',
    group: '系统管理',
  },
  {
    code: 'role:delete',
    name: '角色删除',
    group: '系统管理',
  },
  {
    code: 'menu:view',
    name: '菜单查看',
    group: '系统管理',
  },
  {
    code: 'menu:add',
    name: '菜单新增',
    group: '系统管理',
  },
  {
    code: 'menu:edit',
    name: '菜单编辑',
    group: '系统管理',
  },
  {
    code: 'menu:delete',
    name: '菜单删除',
    group: '系统管理',
  },
  {
    code: 'dept:view',
    name: '部门查看',
    group: '系统管理',
  },
  {
    code: 'dept:add',
    name: '部门新增',
    group: '系统管理',
  },
  {
    code: 'dept:edit',
    name: '部门编辑',
    group: '系统管理',
  },
  {
    code: 'dept:delete',
    name: '部门删除',
    group: '系统管理',
  },
  {
    code: 'commerce:restaurant:view',
    name: '商家查看',
    group: '业务管理',
  },
  {
    code: 'commerce:restaurant:add',
    name: '商家新增',
    group: '业务管理',
  },
  {
    code: 'commerce:restaurant:edit',
    name: '商家编辑',
    group: '业务管理',
  },
  {
    code: 'commerce:restaurant:delete',
    name: '商家删除',
    group: '业务管理',
  },
  {
    code: 'commerce:food:view',
    name: '商品查看',
    group: '业务管理',
  },
  {
    code: 'commerce:food:add',
    name: '商品新增',
    group: '业务管理',
  },
  {
    code: 'commerce:food:edit',
    name: '商品编辑',
    group: '业务管理',
  },
  {
    code: 'commerce:food:delete',
    name: '商品删除',
    group: '业务管理',
  },
  {
    code: 'commerce:order:view',
    name: '订单查看',
    group: '业务管理',
  },
  {
    code: 'commerce:order:accept',
    name: '订单接单',
    group: '业务管理',
  },
  {
    code: 'commerce:order:prepare',
    name: '订单制作',
    group: '业务管理',
  },
  {
    code: 'commerce:order:deliver',
    name: '订单配送',
    group: '业务管理',
  },
  {
    code: 'commerce:order:complete',
    name: '订单完成',
    group: '业务管理',
  },
  {
    code: 'commerce:order:refund:approve',
    name: '同意退款',
    group: '业务管理',
  },
  {
    code: 'commerce:order:refund:reject',
    name: '驳回退款',
    group: '业务管理',
  },
  {
    code: 'commerce:order:edit',
    name: '订单编辑',
    group: '业务管理',
  },
  {
    code: 'merchant:onboarding:view',
    name: '商家入驻审批查看',
    group: '业务管理',
  },
  {
    code: 'merchant:onboarding:review',
    name: '商家入驻审批处理',
    group: '业务管理',
  },
  {
    code: 'merchant:onboarding:approve',
    name: '商家入驻审批通过',
    group: '业务管理',
  },
  {
    code: 'merchant:onboarding:reject',
    name: '商家入驻审批驳回',
    group: '业务管理',
  },
  {
    code: 'monitor:online:view',
    name: '在线用户查看',
    group: '系统监控',
  },
  {
    code: 'monitor:online:force-logout',
    name: '强制下线',
    group: '系统监控',
  },
  {
    code: 'log:login:view',
    name: '登录日志查看',
    group: '系统监控',
  },
  {
    code: 'log:operation:view',
    name: '操作日志查看',
    group: '系统监控',
  },
  {
    code: 'log:system:view',
    name: '系统日志查看',
    group: '系统监控',
  },
  {
    code: 'platform:tenant:view',
    name: '租户查看',
    group: '平台管理',
  },
  {
    code: 'platform:tenant:create',
    name: '租户新增',
    group: '平台管理',
  },
  {
    code: 'platform:tenant:update',
    name: '租户编辑',
    group: '平台管理',
  },
  {
    code: 'platform:tenant:transition',
    name: '租户状态变更',
    group: '平台管理',
  },
]

export const pagePermissions: PagePermissionRecord[] = [
  {
    path: '/dashboard/index',
    name: 'DashboardView',
    title: '仪表盘',
    roles: ['admin', 'user'],
    auths: [],
  },
  {
    path: '/permission/page',
    name: 'PagePermission',
    title: '页面权限',
    roles: ['admin', 'user'],
    auths: ['permission:page:view'],
  },
  {
    path: '/permission/button',
    name: 'ButtonPermission',
    title: '按钮权限',
    roles: ['admin', 'user'],
    auths: ['permission:button:view'],
  },
  {
    path: '/monitor/online-user',
    name: 'OnlineUser',
    title: '在线用户',
    roles: ['admin'],
    auths: ['monitor:online:view'],
  },
  {
    path: '/monitor/login-logs',
    name: 'LoginLogs',
    title: '登录日志',
    roles: ['admin'],
    auths: ['log:login:view'],
  },
  {
    path: '/monitor/operation-logs',
    name: 'OperationLogs',
    title: '操作日志',
    roles: ['admin'],
    auths: ['log:operation:view'],
  },
  {
    path: '/monitor/system-logs',
    name: 'SystemLogs',
    title: '系统日志',
    roles: ['admin'],
    auths: ['log:system:view'],
  },
  {
    path: '/system/user',
    name: 'UserList',
    title: '用户管理',
    roles: ['admin'],
    auths: ['user:view'],
  },
  {
    path: '/system/role',
    name: 'RoleManagement',
    title: '角色管理',
    roles: ['admin'],
    auths: ['role:view'],
  },
  {
    path: '/system/menu',
    name: 'MenuManagement',
    title: '菜单管理',
    roles: ['admin'],
    auths: ['menu:view'],
  },
  {
    path: '/system/dept',
    name: 'DeptManagement',
    title: '部门管理',
    roles: ['admin'],
    auths: ['dept:view'],
  },
  {
    path: '/commerce/restaurant',
    name: 'CommerceRestaurantView',
    title: '商家管理',
    roles: ['admin'],
    auths: ['commerce:restaurant:view'],
  },
  {
    path: '/commerce/food',
    name: 'CommerceFoodView',
    title: '商品管理',
    roles: ['admin'],
    auths: ['commerce:food:view'],
  },
  {
    path: '/commerce/order',
    name: 'CommerceOrderView',
    title: '订单管理',
    roles: ['admin'],
    auths: ['commerce:order:view'],
  },
  {
    path: '/commerce/merchant-onboarding',
    name: 'MerchantOnboardingView',
    title: '商家入驻审批',
    roles: ['admin'],
    auths: ['merchant:onboarding:view'],
  },
  {
    path: '/platform/tenant',
    name: 'PlatformTenantView',
    title: '租户管理',
    roles: ['admin'],
    auths: ['platform:tenant:view'],
  },
  {
    path: '/nested/menu1/menu1-1',
    name: 'NestedMenu11View',
    title: '菜单1-1',
    roles: ['admin', 'user'],
    auths: [],
  },
  {
    path: '/nested/menu1/menu1-2/menu1-2-1',
    name: 'NestedMenu121View',
    title: '菜单1-2-1',
    roles: ['admin', 'user'],
    auths: [],
  },
  {
    path: '/nested/menu1/menu1-2/menu1-2-2',
    name: 'NestedMenu122View',
    title: '菜单1-2-2',
    roles: ['admin', 'user'],
    auths: [],
  },
  {
    path: '/nested/menu1/menu1-3',
    name: 'NestedMenu13View',
    title: '菜单1-3',
    roles: ['admin', 'user'],
    auths: [],
  },
  {
    path: '/nested/menu2',
    name: 'NestedMenu2View',
    title: '菜单2',
    roles: ['admin', 'user'],
    auths: [],
  },
]
